import type {
  BaziCalculationResult,
  ConversationMessage,
  PersonalityProfile,
  UserMemory,
} from "../../types/domain/index.ts";

export const calculation: BaziCalculationResult = {
  chart: {
    id: "chart-ai-1",
    birthProfileId: "birth-ai-secret-id",
    pillars: {
      year: {
        stem: "jia",
        branch: "zi",
        stemElement: "wood",
        stemPolarity: "yang",
        branchElement: "water",
        hiddenStems: [{ stem: "gui", weight: 1, tenGod: "zheng_yin" }],
        tenGod: "bi_jian",
      },
      month: {
        stem: "bing",
        branch: "yin",
        stemElement: "fire",
        stemPolarity: "yang",
        branchElement: "wood",
        hiddenStems: [{ stem: "jia", weight: 0.6, tenGod: "bi_jian" }],
        tenGod: "shi_shen",
      },
      day: {
        stem: "jia",
        branch: "chen",
        stemElement: "wood",
        stemPolarity: "yang",
        branchElement: "earth",
        hiddenStems: [{ stem: "wu", weight: 0.5, tenGod: "pian_cai" }],
      },
      hour: {
        stem: "geng",
        branch: "wu",
        stemElement: "metal",
        stemPolarity: "yang",
        branchElement: "fire",
        hiddenStems: [{ stem: "ding", weight: 0.7, tenGod: "shang_guan" }],
        tenGod: "qi_sha",
      },
    },
    dayMaster: { stem: "jia", element: "wood", polarity: "yang" },
    calculatedAt: "2026-08-18T00:00:00.000Z",
  },
  calculationMetadata: {
    engine_version: "bazi-engine/1.0.0",
    rule_profile_version: "rules/1.0.0",
    sourceTimezone: "Asia/Kuala_Lumpur",
    calendarConversion: "gregorian_to_solar_terms",
    birthTimeWasKnown: true,
    calculatedAt: "2026-08-18T00:00:00.000Z",
    warnings: [],
  },
  derivedFeatures: {
    id: "derived-ai-1",
    chartId: "chart-ai-1",
    engine_version: "bazi-engine/1.0.0",
    rule_profile_version: "rules/1.0.0",
    mapping_version: "personality-map/0.2.0",
    dayMasterStrength: "balanced",
    elementDistribution: [
      { element: "wood", score: 32 },
      { element: "fire", score: 25 },
      { element: "earth", score: 18 },
      { element: "metal", score: 15 },
      { element: "water", score: 10 },
    ],
    tenGodDistribution: [
      { tenGod: "bi_jian", score: 18 },
      { tenGod: "jie_cai", score: 5 },
      { tenGod: "shi_shen", score: 15 },
      { tenGod: "shang_guan", score: 12 },
      { tenGod: "pian_cai", score: 14 },
      { tenGod: "zheng_cai", score: 8 },
      { tenGod: "qi_sha", score: 13 },
      { tenGod: "zheng_guan", score: 4 },
      { tenGod: "pian_yin", score: 6 },
      { tenGod: "zheng_yin", score: 5 },
    ],
    seasonalContext: "木气有根，结构整体较均衡。",
    structuralTags: ["balanced_elements", "visible_expression", "adaptive_drive"],
    confidence: 0.88,
    derivedAt: "2026-08-18T00:00:01.000Z",
  },
  relations: [
    {
      kind: "branch_clash",
      leftPillar: "year",
      rightPillar: "hour",
      left: "zi",
      right: "wu",
    },
  ],
  luck: {
    direction: "forward",
    startAgeYears: 6,
    boundaryTerm: "jing_zhe",
    boundaryInstant: "2026-03-05T00:00:00.000Z",
    method: "three_days_one_year",
    warnings: [],
    cycles: [1, 2, 3, 4, 5].map((index) => ({
      index,
      pillar: index % 2 === 0 ? { stem: "bing" as const, branch: "yin" as const } : { stem: "yi" as const, branch: "chou" as const },
      startAgeYears: 6 + (index - 1) * 10,
      endAgeYears: 15 + (index - 1) * 10,
    })),
  },
};

export const personality: PersonalityProfile = {
  id: "personality-ai-1",
  chartId: "chart-ai-1",
  mapping_version: "personality-map/0.2.0",
  summary: "自主、表达与现实适配之间有明显的动态平衡。",
  dimensions: [
    { key: "autonomy", label: "自主性", score: 72, confidence: 0.86, evidenceKeys: ["autonomy.bi_jian"] },
    { key: "expression_drive", label: "表达驱动力", score: 68, confidence: 0.82, evidenceKeys: ["expression.shi_shen"] },
    { key: "planning_orientation", label: "规划倾向", score: 54, confidence: 0.75, evidenceKeys: ["planning.earth"] },
  ],
  strengths: ["能自主推进", "表达有个人风格", "适应变化"],
  growthEdges: ["高压时容易同时想控制和突破"],
  behaviorSuggestions: ["重要决策先写下目标与边界", "把探索拆成低成本实验"],
  generatedAt: "2026-08-18T00:00:02.000Z",
};

export const memories: UserMemory[] = Array.from({ length: 10 }, (_, index) => ({
  id: `memory-${index + 1}`,
  userId: "user-ai-1",
  conversationId: "conversation-ai-1",
  key: index === 0 ? "career_goal" : index === 1 ? "conversation_summary:conversation-ai-1" : `memory_${index + 1}`,
  kind: index === 0 ? "goal" : index === 2 ? "constraint" : "preference",
  value: index === 0 ? "希望找到更自主的工作方式" : `memory value ${index + 1}`,
  confidence: 0.9,
  userEditable: true,
  active: index !== 9,
  createdAt: `2026-08-18T00:00:${String(index).padStart(2, "0")}.000Z`,
  updatedAt: `2026-08-18T00:01:${String(index).padStart(2, "0")}.000Z`,
}));

export const messages: ConversationMessage[] = Array.from({ length: 12 }, (_, index) => ({
  id: `message-${index + 1}`,
  conversationId: "conversation-ai-1",
  userId: "user-ai-1",
  role: index === 2 ? "system" : index % 2 === 0 ? "user" : "assistant",
  content: `message content ${index + 1}`,
  creditCost: 0,
  createdAt: `2026-08-18T00:02:${String(index).padStart(2, "0")}.000Z`,
}));
